config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :pages do
    collection do
      get :about
    end
  end
  resources :categories
  resources :quiz do
    collection do
      get :question
      get :summary
    end
    get :review
  end
  resources :analytics do
    collection do
      get :summary
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
  has_many :quizzes

  def create_quiz
  	lbl = "Quiz" + (Quiz.last.id + 1)
  	quiz = self.quizzes.create!(name: lbl)
  	return quiz
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  has_many :user_inputs
end

app/models/json_builder.rb
class JsonBuilder
  attr_reader :user
  def initialize(user)
    @user = user
  end

  def build
    user_json = {}
    user_json["total_questions"] = Question.count
    user_json["questions_answered"] = entries.count
    user_json["correct_answers"] = entries.correct_answers.count
    user_json["incorrect_answers"] = entries.incorrect_answers.count
    user_json["questions_remaining"] = user_json["total_questions"] - user_json["questions_answered"]
    return user_json
  end

  def entries
    user.user_inputs
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :choices
  belongs_to :category
  has_many :user_inputs

  def next_question(question_ids)
  	next_index =  question_ids.index(id) + 1
    next_question_id = question_ids.at(next_index)
    next_question_id.present? ? Question.find(next_question_id) : nil
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :user_inputs
  belongs_to :category

  def self.filter(params,user)
  	question_ids = split_question_ids(params[:quelist])
    next_question = Question.find(params[:question_id]).next_question(question_ids)
    quiz = Quiz.find_by_id(params[:quiz])
    entry = user.create_quiz_entry(params[:choice], question_ids, quiz)
    score = next_question.nil? ? entry : nil
    [question_ids, next_question, quiz, score]
  end

  def self.split_question_ids(list)
  	list.split().map(&:to_i)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_inputs

  def create_quiz_entry(choice_id, questions, quiz)
    choice = Choice.find(choice_id)
    UserInput.create!(user: self, choice: Choice.find(choice_id),
                        question: choice.question, correct_answer: choice.correct, quiz: quiz)
    return user_inputs.where(question: questions, correct_answer: true, quiz: quiz).count
  end

  def calculate_progress
    return ["positive-review", "You are yet to take quiz. All the best!"] if user_inputs.count.zero?
    percentage = (user_inputs.correct_answers.count*100)/(user_inputs.count)
    return ["positive-review", "You are doing great! Go ahead !"] if percentage >= 60
    return ["negative-review", "You need more practice. Practice hard."] if percentage < 60
  end
end

app/models/user_input.rb
class UserInput < ApplicationRecord
  belongs_to :user
  belongs_to :choice
  belongs_to :question 
  belongs_to :quiz

  scope :correct_answers, -> { where(correct_answer: true) }
  scope :incorrect_answers, -> { where(correct_answer: false) }

  def questions(category)
  	where(question: category.questions)
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
  end

  def summary
    json_data = JsonBuilder.new(current_user).build
    render json: json_data, status: 200
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all.pluck(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
    @quiz = Quiz.find(current_user.user_inputs.pluck(:quiz_id))
  end

  def review
    @quiz = Quiz.find(params[:quiz_id])
    @user_inputs = @quiz.user_inputs
    @count = 5 # in this case its 5 always otherwise will need to retrieve it from database
  end

  def summary
    @categories = Category.all
  end

  def question
    @category = category(params)
    if params[:question_id].present?
      @question_ids, @next_question, @quiz, @score = Quiz.filter(params, current_user)
    else
      @question_ids = question_ids_for_quiz(params)
      if @question_ids.empty?
        @message = "No more questions left"
      else
        @next_question = Question.find(@question_ids.first)
        @quiz = quiz
      end
    end
    @choices = @next_question.choices if @next_question.present?
  end

private
  def category(params)
    @category ||= Category.find_by_name(params[:category])
  end

  def question_ids_for_quiz(params)
    return category(params).nil? ? ids(Question.all) : ids(category(params).questions)
  end

  def ids(questions)
    return questions.where.not(id: current_user.user_inputs.pluck(:question_id)).sample(5).pluck(:id)
  end

  def quiz
    last_quiz_id = Quiz.last.try(:id).nil? ? 1 : Quiz.last.try(:id)+1
    lbl = "Quiz #{last_quiz_id}"
    quiz = Quiz.new(name: lbl, category: @category)
    quiz.save(validate: false)
    return quiz
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analytics/index.html.erb
<html>
  <head>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      $(document).ready(function() {
        google.charts.load('current', {'packages':['bar']});
        google.charts.load('current', {'packages':['corechart']});
        $.ajax({
          method: 'GET',
          url: 'http://localhost:3000/analytics/summary',
          dataType: 'json',
          success: function(data){
            window.info_json = data;
          }
        });
        google.charts.setOnLoadCallback(drawBarChart1);
        google.charts.setOnLoadCallback(drawBarChart2);
        google.charts.setOnLoadCallback(drawPieChart1);
        google.charts.setOnLoadCallback(drawPieChart2);
        function drawBarChart1(){
          var data = google.visualization.arrayToDataTable([
            ['Questions', 'Count'],
            ["Answered", window.info_json["questions_answered"]],
            ["Unanswered", window.info_json["questions_remaining"]]
          ]);
          var options = {
            bars: 'vertical',
            colors: ['#dc7633']
          };
          var chart1 = new google.charts.Bar(document.getElementById('bar_graph1'));
          chart1.draw(data, google.charts.Bar.convertOptions(options));
        }
        function drawBarChart2(){
          var data = google.visualization.arrayToDataTable([
            ['Questions', 'Count'],
            ["Correct Answers", window.info_json["correct_answers"]],
            ["Incorrect Answers", window.info_json["incorrect_answers"]]
          ]);
          var options = {
            bars: 'vertical',
            colors:['#f5b041']
          };
          var chart2 = new google.charts.Bar(document.getElementById('bar_graph2'));
          chart2.draw(data, google.charts.Bar.convertOptions(options)); 
        }
        function drawPieChart1() {
          var data = google.visualization.arrayToDataTable([
            ['Questions', 'Count'],
            ["Answered", window.info_json["questions_answered"]],
            ["Unanswered", window.info_json["questions_remaining"]]
          ]);
          var options = {
            title: 'Quiz Summary',
            colors: ['green', 'red']
          };
          var chart = new google.visualization.PieChart(document.getElementById('piechart1'));
          chart.draw(data, options);
        }
        function drawPieChart2() {
          var data = google.visualization.arrayToDataTable([
            ['Questions', 'Count'],
            ["Correct Answers", window.info_json["correct_answers"]],
            ["Incorrect Answers", window.info_json["incorrect_answers"]]
          ]);
          var options = {
            title: 'Solved Quiz Summary',
            colors: ['green', 'red']
          };
          var chart = new google.visualization.PieChart(document.getElementById('piechart2'));
          chart.draw(data, options);
        }
      });
    </script>
  </head>
  <body>
    <center>
      <div id="error">Click <b>Graphical Summary tab</b> again if page not loaded properly</div>
      <div class="row " style="margin-top: 20px;">
        <div class="col-md-6 positive-review" style="margin-left:140px;"> Quiz Summary</div>
        <div class="col-md-6 positive-review" style="margin-left:270px;"> Solved Quiz Summary</div>
      </div>
      <div class="row" style="margin-top: 30px;">
        <div class="col-md-6">
          <div id='bar_graph1' style="width: 450px; height: 250px;">
            <%= image_tag('loadingimage.gif', height: '200')%>
          </div>
        </div>
        <div class="col-md-6">
          <div id='bar_graph2' style="width: 450px; height: 250px;">
            <%= image_tag('loadingimage.gif', height: '200')%>
          </div>
        </div>
      </div>
      <div class="row" style="margin-top: 30px;">
        <div class="col-md-6">
          <div id='piechart1' style="width: 450px; height: 200px;">
            <%= image_tag('loadingimage.gif', height: '200')%>
          </div>
        </div>
        <div class="col-md-6">
          <div id='piechart2' style="width: 450px; height: 200px;">
            <%= image_tag('loadingimage.gif', height: '200')%>
          </div>
        </div>
      </div>
    </center>
  </body>
</html>

app/views/categories/index.html.erb
<div class="authform">
    <div><center class="heading">Welcome <%= current_user.name %></center></div>
    <%= image_tag 'start_quiz.png' %>
	<%= form_tag question_quiz_index_path, method: 'GET', class: 'form-inline' do  %>
	  <div class='form-group'>
	    <h4><center class="inner_heading">Select Quiz category</center></h4>
	    <hr>
	    <center><%= select_tag 'category', options_for_select(@categories), prompt: 'All categories', class: 'form-control' %></center>
	  </div>
	  <hr>
	  <center>
		  <div class='form-group'>
            <%= submit_tag 'Start Quiz', :class=>'btn btn-default' do %>
              <span class="glyphicon glyphicon-off"></span>
            <% end %>
		  </div>
		</center>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Quiz Categories', categories_path %></li>
  <li><%= link_to 'Quiz Summary', quiz_index_path %></li>
  <li><%= link_to 'Question Summary', summary_quiz_index_path %></li>
  <li><%= link_to 'Graphical Summary', analytics_path %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <a href='#' class='navbar-brand'>Welcome <%= current_user.name %></a>
  <li>
    <%= link_to destroy_user_session_path, :method=>'delete' do %>
      <span class="glyphicon glyphicon-off"></span>
    <% end %>
  </li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '', class: 'navbar-brand', style: 'margin-left: -114px; font-size: 18px' do %>
        <i class="glyphicon glyphicon-question-sign"></i>&nbsp;&nbsp;Online Quiz
      <% end %>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quiz Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Quiz Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<ul class='sticky'>
  <li class='sticky'>
    <a href="#" class='a_sticky'>
      <%= image_tag "AboutUS.jpeg" %>
      <hr class='hr_blue'>
      <h2>About Website</h2>
      <hr class='hr_blue'>
      <p>To build a multiple choice web application.</p>
      <p>
        <span>» ‘Welcome’ style screen that shows information about</span><br>
        <span>&nbsp;&nbsp;- Available Questions</span><br>
        <span>&nbsp;&nbsp;- Already taken Questions</span><br>
        <span>» Multiple choice questions with a category assigned to it.</span><br>
        <span>» Review Quiz.</span><br>
        <span>» Start Quiz.</span>
      </p>
    </a>
  </li>
  <li class='sticky'>
    <a href="#" class='a_sticky'>
      <%= image_tag "programming_languages.jpeg" %>
      <hr class='hr_blue'>
      <h2>Technologies:</h2>
      <hr class='hr_blue'>
      <span>» Ruby on Rails</span><br>
      <span>» HTML</span><br>
      <span>» CSS</span><br>
      <span>» JavaScript</span><br>
      <span>» SQLite</span>
    </a>
  </li>
  <li class='sticky'>
    <a href="#" class='a_sticky'>
      <%= image_tag "functionality.jpeg" %>
      <hr class='hr_blue'>
      <h2>Functionalities:</h2>
      <hr class='hr_blue'>
      <span>» Start Quiz.</span><br>
      <span>» Review Quiz.</span><br>
      <span>» Quiz Summary.</span><br>
      <span>» Overall Summary.</span><br>
      <span>» Graphical Summary.</span>
    </a>
  </li>
</ul>

app/views/quiz/_quiz_question.html.erb
<div class="authform quizwidth quizdetails">
  <div class="row" style='margin-left: 30px;padding-bottom: 20px;'>
    <div class="col-6 col-md-4"><b style='font-size: 18px;'>Quiz Name: </b></span><%= quiz.name %></div>
    <div class="col-6 col-md-4"><b style='font-size: 18px;'>Participant Name: </b></span><%= current_user.name %></div>
    <div class="col-6 col-md-4"><b style='font-size: 18px;'>Question: </b></span><%= quelist.index(question.id)+1 %> / <%= quelist.length %></div>
  </div>
</div>
<div class="authform quizwidth">
  <%= form_tag question_quiz_index_path, method: 'GET', class: 'form-inline' do  %>
    <div class='form-group'>
      <%= hidden_field_tag :question_id, question.id %>
      <%= hidden_field_tag :category, category.try(:name) %>
      <%= hidden_field_tag :quelist, quelist %>
      <%= hidden_field_tag :quiz, quiz.id %>

      <% lines = question.text.split("<br />") %>
      <% lines.each do |li| %>
        <%= li %><br>
      <% end %>
    </div>
    <hr>
    <% choices.each do |option| %>
      &nbsp;&nbsp;&nbsp;&nbsp;<%= radio_button_tag 'choice', option.id, required: true %>&nbsp;&nbsp;&nbsp;&nbsp;<span><%= option.text %></span><br>
    <% end %>
    <hr>
    <center>
      <div class='form-group nextbutton'>
        <%= submit_tag 'Next Question', :class=>'btn btn-default btn-quiz' %>
      </div>
    </center>
  <% end %>
</div>

app/views/quiz/_quiz_thankyou.html.erb
<div class="margin-image">
  <%= image_tag src="thankyou.png", height: '50%', width: '50%'%>
</div>
<center>
  <h4><b>Final Score for Quiz :</b></h4>
  <%= score %> of <%= quelist.length %><br>
  <b><%= (score*100/quelist.length) %> %</b><br><br>
  <b>
    <% if score == quelist.length %>
      Perfect!!
    <% elsif score >= quelist.length-2 %>
      You are doing good!!
    <% else %>
      Improve your score!!
    <% end %>
  </b>
</center>
<br>
<center>
  <div class="form-group">
    <p><%= link_to 'Review Submission', quiz_review_path(quiz.id), :class=>'btn btn-info' %></p>
  </div>
</center>

app/views/quiz/index.html.erb
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #EBF5FB;
  }
</style>
<div class="container">
  <div class="row">
    <div class="authform quizwidth quizdetails" style='padding-bottom:20px;'>
      <b style='margin-left:15px;'>Quiz Summary</b> for <%= current_user.name %>
    </div>
    <br>
    <center>
      <% if @quiz.empty? %>
        <p class = "positive-review"><b>You have not taken any quiz yet.</b></p>
      <% else %>
        <div>
          <table class="table">
            <tbody>
              <tr>
                <td><b>Category</td>
                <td><b>Quiz Name</td>
                <td><b>Number of Questions</td>
                <td><b>Score</td>
                <td><b>Review</td> 
              </tr>
              <% @quiz.each do |quiz| %>
                <tr>
                  <td><%= quiz.category.try(:name).nil? ? "All Categories" : quiz.category.try(:name) %></td>
                  <td><%= quiz.name %></td>
                  <td><%= quiz.user_inputs.count %></td>
                  <td><%= quiz.user_inputs.where(correct_answer: true).count %></td>
                  <td>
                    <%= link_to quiz_review_path(quiz.id) do %>
                      <span class="glyphicon glyphicon-search"></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </center>
  </div>
</div>

app/views/quiz/question.html.erb
<% if @message.present? %>
  <div class="container" style = "margin-top: 5%">
    <div class="row">
      <center>
        <p class = "positive-review"><b><%= @message %></b></p>
        <p style = "margin-top: 2%"><%= link_to 'Select another category', categories_path %></p>
      </center>
    </div>
  </div>
<% elsif @next_question.present? %>
  <%= render 'quiz_question', question: @next_question, choices: @choices, category: @category, quelist: @question_ids, quiz: @quiz %>
<% else %>
  <%= render 'quiz_thankyou', score: @score, quiz: @quiz, quelist: @question_ids %>
<% end %>

app/views/quiz/review.html.erb
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td, th {
    border: 1px solid #ABB2B9;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #EBF5FB;
  }
</style>
<div class="container">
  <div class="row">
    <center>
      <br>
      <div class="authform quizwidth quizdetails">
        <div class="row" style='padding-bottom: 20px;'>
          <div class="col-6 col-md-6"><b style='font-size: 18px;'>Quiz Name: </b></span><%= @quiz.name %></div>
          <div class="col-6 col-md-6"><b style='font-size: 18px;'>Participant Name: </b></span><%= current_user.name %></div>
        </div>
      </div>
      <br>
      <div>
        <table class="table">
          <tbody>
            <tr>
              <td><b>Question</b></td>
              <% (1..@count).each do |i| %>
              <td><b>Option <%= i %></b></td>
              <% end %>
              <td><b>Your Answer</b></td>
            </tr>
            <% @user_inputs.each do |user_input| %>
              <% question = user_input.question %>
              <tr>
                <% lines = question.text.split("<br />") %>
                <td>
                  <%= lines[0] %><br>
                  <%= lines[2] %>
                </td>
                <% question.choices.each do |choice| %>
                  <% if choice.correct %>
                    <td style="color: green; font-weight: bold"><%= choice.text %></td>
                  <% else %>
                    <td><%= choice.text %></td>
                  <% end %>
                <% end %>
                <% if user_input.correct_answer %>
                  <td style="color: green; font-weight: bold"><%= user_input.choice.text %></td>
                <% else %>
                  <td style="color: red; font-weight: bold"><%= user_input.choice.text %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </center>
  </div>
</div>

app/views/quiz/summary.html.erb
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  td, th {
    border: 1px solid #ABB2B9;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: #EBF5FB;
  }
</style>
<div class="container">
  <div class="row">
    <div class="authform quizwidth quizdetails" style='padding-bottom:20px;'>
      <b style='margin-left:15px;'>Question Summary</b> for <%= current_user.name %>
    </div>
    <br>
    <center>
      <div>
        <table class="table">
          <tbody>
            <tr>
              <td><b>Category</td>
              <td><b>Total Questions</td>
              <td><b>Questions answered</td>
              <td><b>Correct Answers</td>
              <td><b>Incorrect Answers</td>
              <td><b>Questions remaining</td>
            </tr>
            <tr style="background-color: #99ccff">
              <% total = Question.count %>
              <% user_total = current_user.user_inputs %>
              <td>All Categories</td>
              <td><%= total %></td>
              <td><%= user_total.count %></td>
              <td><%= user_total.correct_answers.count %></td>
              <td><%= user_total.incorrect_answers.count %></td>
              <td><%= total - user_total.count %></td>
            <tr>
            <% @categories.each do |category| %>
              <tr>
                <% category_total = category.questions.count %>
                <% user_category_total = current_user.user_inputs.where(question: category.questions) %>
                <td><%= category.name %></td>
                <td><%= category.questions.count %></td>
                <td><%= user_category_total.count %></td>
                <td><%= user_category_total.correct_answers.count %></td>
                <td><%= user_category_total.incorrect_answers.count %></td>
                <td><%= category_total - user_category_total.count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </center>
    <div class="authform quizwidth quizdetails" style='padding-bottom:20px;'>
      <b style='margin-left:15px;'>Progress </b> for <%= current_user.name %>
    </div>
    <% cls, text = current_user.calculate_progress %>
    <div class="authform quizwidth quizdetails" style='padding-bottom:25px;background-color:#FDEDEC;'>
      <b style='color:#C0392B; margin-left:15px;'><%= text %></b>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <center>
      <h3>Users</h3>
      <div class="column" style="left: 25%">
        <table class="table">
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <%= render user %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </center>
  </div>
</div>

app/views/users/show.html.erb
<center>
  <h3>User details</h3>
  <p>Name: <%= @user.name if @user.name %></p>
  <p>Email: <%= @user.email if @user.email %></p>
</center>

app/views/visitors/index.html.erb
<center>
  <%= image_tag "QuizUp_icon.jpeg", :class => "style_image"%>
  <%= image_tag "welcome.jpeg", :class => "style_image_1"%>
</center>